### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by memerich** [thatretrodev/placebot#1]
![image](https://user-images.githubusercontent.com/62115158/162512552-66597144-127e-470a-9c38-16e9bb10df83.png)
how can i fix that

and do you have discord or like smth

**Comment by thatretrodev** [comment]
I really should've made documentation earlier, but I forgot to do that.
I'm going to make this issue about creating the documentation.

**Comment by thatretrodev** [comment]
I added a `How to run` section to `README.md`.
If there's a problem with it, make a comment in this issue and I'll try to fix it.
